In [1]:
import numpy as np

In [2]:
a=np.random.rand(10,1)

In [3]:
a

array([[0.06893252],
       [0.3682801 ],
       [0.6084704 ],
       [0.93614035],
       [0.34506209],
       [0.85624272],
       [0.7385125 ],
       [0.15797423],
       [0.27450691],
       [0.78985852]])

In [4]:
np.mean(a)

0.5143980353100658

In [5]:
b=np.random.rand(20,1)

In [6]:
np.std(a)

0.2937226714448523

In [7]:
np.var(a)

0.08627300772070065

In [8]:
a=np.random.rand(10,20)

In [9]:
b=np.random.rand(20,25)

In [11]:
c=np.dot(a,b)

In [12]:
c

array([[6.39475957, 7.06400425, 5.17543743, 4.71393903, 5.82956921,
        5.92821859, 5.67706084, 6.00981647, 5.53826185, 5.00872476,
        6.87842294, 5.91937168, 6.29890344, 5.70316939, 7.04945388,
        6.01628948, 5.08006069, 6.36093582, 6.21248032, 5.64881836,
        7.86251966, 7.73265165, 7.80226091, 6.76696489, 6.83032681],
       [4.7734969 , 5.16438175, 3.23230487, 3.72448887, 4.10611854,
        3.83809308, 4.41707809, 3.7493083 , 3.65624593, 3.63746944,
        5.06319989, 4.39739935, 4.24423813, 4.01360059, 4.82480801,
        4.09047342, 3.63883692, 3.61134663, 4.98521287, 3.98312716,
        6.10555286, 5.35428499, 5.18507199, 5.01013084, 4.49361673],
       [4.66704564, 5.26834208, 3.50210689, 4.17688709, 3.49052002,
        4.01325305, 4.50764755, 4.2114354 , 3.7243995 , 3.17168942,
        6.11189942, 4.2070423 , 4.82257614, 4.57494043, 4.4900362 ,
        3.63005948, 3.55019692, 4.18368699, 5.30624728, 4.33935927,
        5.53966422, 5.30970653, 5.58266426, 4.

In [14]:
a=np.random.rand(10,1)

In [21]:
import math
def func(a):
    return (1/(1+math.exp(-a)))

In [23]:
for i in range(len(a)):
    a[i]=func(a[i])

In [24]:
a

array([[0.6562994 ],
       [0.5568165 ],
       [0.52241166],
       [0.63237304],
       [0.72288434],
       [0.67794957],
       [0.53886102],
       [0.70689078],
       [0.72374749],
       [0.69921089]])